name: Weekly Data Ingest
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without writing data"
        required: false
        default: "true"
      manual_start_date:
        description: "Beginning date to begin manual run"
        required: false
        default : ""
      manual_end_date:
        description: "End date to begin manual run"
        required: false
        default: ""
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "main"

  schedule:
    - cron: "0 0 * * 1"

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set date range
        run: |
          END_DATE=$(date -u -d "yesterday" +%F)
          START_DATE=$(date -u -d "$END_DATE -6 days" +%F)
          echo "START_DATE=$START_DATE" >> $GITHUB_ENV
          echo "END_DATE=$END_DATE" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingest job
        env:
          APP_TOKEN_API_KEY: ${{ secrets.APP_TOKEN_API_KEY }}
        run: |
          python scripts/pull_rodent_data.py \
            --start-date=$START_DATE \
            --end-date=$END_DATE \
            --manual-start-date=${{github.event.inputs.manual_start_date || ''}} \
            --manual-end-date=${{github.event.inputs.manual_end_date || ''}} \
            --dry-run=${{ github.event.inputs.dry_run || 'false' }}

      - name: Run data processing
        env:
          GEOAPIFY_KEY: ${{ secrets.GEOAPIFY_KEY }}
        run: |
          python scripts/pull_nearby_locations_v2.py \
            --start-date=$START_DATE \
            --end-date=$END_DATE \
            --manual-start-date=${{github.event.inputs.manual_start_date || ''}} \
            --manual-end-date=${{github.event.inputs.manual_end_date || ''}} \
            --dry-run=${{ github.event.inputs.dry_run || 'false' }}
      - name: Aggregate Data
        run: |
          python scripts/final_data.py \
            --dry-run=${{ github.event.inputs.dry_run || 'false' }}

      - name: Commit and push data updates
        if: github.event.inputs.dry_run != 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/raw_data/
          git add data/intermediate_data/
          git add data/final_data/

          # git diff --cached --quiet || 
          git commit -m "Weekly data update"
          git push

